ARG PYTHON_VERSION=3.9

# Production stage
FROM python:${PYTHON_VERSION}-alpine

# Create a non-root user
RUN adduser -D -s /bin/ash myuser && \
    apk update && \
    apk add sudo && \
    echo "myuser ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# Set environment variables
ENV CONTAINER_APP_PORT=80 \
    WORKDIR=/usr/src/app \
    PYTHONPATH=. \
    PATH="/home/myuser/.local/bin:${PATH}" \
    OUTPUT_FILE_PATH=/var/lib/nginx/html/myclock.html

# Set the working directory
WORKDIR ${WORKDIR}

# Install nginx
RUN apk add --no-cache nginx && \
    mkdir -p /run/nginx

COPY nginx-alpine.conf /etc/nginx/nginx.conf

# Set correct permissions
RUN chown -R myuser:myuser /var/log/nginx /var/lib/nginx /run/nginx && \
    chmod 755 /var/log/nginx /var/lib/nginx /run/nginx

# Copy requirements file
COPY --chown=myuser:myuser requirements-base.txt ./

# Switch to non-root user
USER myuser

# Install base Python packages
RUN pip -v install --user pip && \
    pip -v install -r requirements-base.txt

# Copy application code
COPY --chown=myuser:myuser my_clock.py ./
# Copy the entrypoint script
COPY --chown=myuser:myuser entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

# Expose the container port
EXPOSE ${CONTAINER_APP_PORT}

# Set the entrypoint
ENTRYPOINT ["./entrypoint.sh"]
